//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowAppMain
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersNotes
    {
        public int IDUser { get; set; }
        public System.DateTime DateNote { get; set; }
        public string Para { get; set; }
        public int ParaNumber { get; set; }
        public string NoteText { get; set; }
    }
}
