//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowAppMain.Model.DataBaseEF.DBManagerbot
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersInfo
    {
        public int ID { get; set; }
        public string UserName { get; set; }
        public string UserStatus { get; set; }
        public string UserDepartment { get; set; }
        public string UserGroup { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
