//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowAppMain.Model.DataBaseEF.DBManagerbot
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int ID { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
    
        public virtual UsersNotes UsersNotes { get; set; }
        public virtual UsersInfo UsersInfo { get; set; }
    }
}
